**Importing** the **libraries**

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.3.0'

**Data** **Preprocessing**

In [ ]:
churn_modeling=pd.read_csv('drive/My Drive/Churn_Modelling.csv')
churn_modeling.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
c=churn_modeling.copy()
c.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
churn_modeling.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)
churn_modeling.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [ ]:
churn_modeling.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
X=churn_modeling.drop('Exited',axis=1).values

In [ ]:
y=churn_modeling['Exited'].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
X[:,2]=lb.fit_transform(X[:,2])

In [ ]:
print(X)
print(X.shape)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
(10000, 10)


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
print(X)
print(X.shape)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
(10000, 12)


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

**feature Scaling  :**  Feature Scaling is compulsory for deep learning

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
print(X_train.shape)

(8000, 12)


**Creating ANN**

In [ ]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

**Compiling the model**

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

**Fitting model on training dataset**

In [ ]:
ann.fit(X_train,y_train,batch_size=35,epochs=100)

Epoch 1/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4889 - accuracy: 0.7960
Epoch 2/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4482 - accuracy: 0.7960
Epoch 3/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.7960
Epoch 4/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4315 - accuracy: 0.7960
Epoch 5/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4278 - accuracy: 0.7986
Epoch 6/100
229/229 [==============================] - 0s 1ms/step - loss: 0.4242 - accuracy: 0.8114
Epoch 7/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4200 - accuracy: 0.8202
Epoch 8/100
229/229 [==============================] - 0s 2ms/step - loss: 0.4151 - accuracy: 0.8260
Epoch 9/100
229/229 [==============================] - 0s 1ms/step - loss: 0.4101 - accuracy: 0.8304
Epoch 10/100
229/229 [==============================] - 0s 1ms/step - loss: 0.4045 - accura

In [ ]:
output=ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

In [ ]:
print(output)

[[False]]


In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Validating the model by Using different metrics**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm


array([[1535,   60],
       [ 218,  187]])

In [ ]:
accuracy_score(y_test,y_pred)

0.861